# fonts
PRODUCT_COPY_FILES += \
    vendor/rebellion/prebuilt/common/fonts/Abel-Regular.ttf:system/fonts/Abel-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/AdamCGPro-Regular.ttf:system/fonts/AdamCGPro-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/AdventPro-Regular.ttf:system/fonts/AdventPro-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/AlexanaNeue-Regular.ttf:system/fonts/AlexanaNeue-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/AlienLeague-Regular.ttf:system/fonts/AlienLeague-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/ArchivoNarrow-Regular.ttf:system/fonts/ArchivoNarrow-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/AutourOne-Regular.ttf:system/fonts/AutourOne-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Azedo-Light.ttf:system/fonts/Azedo-Light.ttf \
    vendor/rebellion/prebuilt/common/fonts/BadScript-Regular.ttf:system/fonts/BadScript-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/BigNoodleTilting-Regular.ttf:system/fonts/BigNoodleTilting-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Biko-Regular.ttf:system/fonts/Biko-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Blern-Regular.ttf:system/fonts/Blern-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/burnstown/burnstown.ttf:system/fonts/Burnstown-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/CherrySwash-Regular.ttf:system/fonts/CherrySwash-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Cocon-Regular.ttf:system/fonts/Cocon-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Codystar.ttf:system/fonts/Codystar.ttf \
    vendor/rebellion/prebuilt/common/fonts/dumbledor/dumbledor.ttf:system/fonts/Dumbledor-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Fester-Medium.ttf:system/fonts/Fester-Medium.ttf \
    vendor/rebellion/prebuilt/common/fonts/FoxAndCat-Regular.ttf:system/fonts/FoxAndCat-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/GinoraSans-Regular.ttf:system/fonts/GinoraSans-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/gobold/Gobold.ttf:system/fonts/Gobold.ttf \
    vendor/rebellion/prebuilt/common/fonts/gobold/Gobold-Italic.ttf:system/fonts/Gobold-Italic.ttf \
    vendor/rebellion/prebuilt/common/fonts/gobold/GoboldBold.ttf:system/fonts/GoboldBold.ttf \
    vendor/rebellion/prebuilt/common/fonts/gobold/GoboldBold-Italic.ttf:system/fonts/GoboldBold-Italic.ttf \
    vendor/rebellion/prebuilt/common/fonts/gobold/GoboldThinLight.ttf:system/fonts/GoboldThinLight.ttf \
    vendor/rebellion/prebuilt/common/fonts/gobold/GoboldThinLight-Italic.ttf:system/fonts/GoboldThinLight-Italic.ttf \
    vendor/rebellion/prebuilt/common/fonts/IBMPlexMono.ttf:system/fonts/IBMPlexMono.ttf \
    vendor/rebellion/prebuilt/common/fonts/Inkferno-Regular.ttf:system/fonts/Inkferno-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Instruction-Regular.ttf:system/fonts/Instruction-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/JackLane-Regular.ttf:system/fonts/JackLane-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Jura-Regular.ttf:system/fonts/Jura-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/KellySlab-Regular.ttf:system/fonts/KellySlab-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Metropolis1920-Regular.ttf:system/fonts/Metropolis1920-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Monad-Regular.ttf:system/fonts/Monad-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/mexcellent/mexcellent.ttf:system/fonts/Mexcellent-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Noir-Regular.ttf:system/fonts/Noir-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/North-Regular.ttf:system/fonts/North-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/OutrunFuture-Regular.ttf:system/fonts/OutrunFuture-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Pompiere-Regular.ttf:system/fonts/Pompiere-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/PhantomBold/PhantomBold.ttf:system/fonts/PhantomBold-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Qontra-Regular.ttf:system/fonts/Qontra-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Raleway-Light.ttf:system/fonts/Raleway-Light.ttf \
    vendor/rebellion/prebuilt/common/fonts/ReemKufi-Regular.ttf:system/fonts/ReemKufi-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/roadrage/road_rage.ttf:system/fonts/RoadRage-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Riviera-Regular.ttf:system/fonts/Riviera-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Satisfy-Regular.ttf:system/fonts/Satisfy-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/SeaweedScript-Regular.ttf:system/fonts/SeaweedScript-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/SedgwickAveDisplay-Regular.ttf:system/fonts/SedgwickAveDisplay-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Shamshung/Shamshung.ttf:system/fonts/Shamshung.ttf \
    vendor/rebellion/prebuilt/common/fonts/snowstorm/snowstorm.ttf:system/fonts/Snowstorm-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/ThemeableClock-vcrosd.ttf:system/fonts/ThemeableClock-vcrosd.ttf \
    vendor/rebellion/prebuilt/common/fonts/TheOutbox-Regular.ttf:system/fonts/TheOutbox-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Union-Regular.ttf:system/fonts/Union-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Vibur.ttf:system/fonts/Vibur.ttf \
    vendor/rebellion/prebuilt/common/fonts/vcrosd/vcr_osd_mono.ttf:system/fonts/ThemeableFont-Regular.ttf \
    vendor/rebellion/prebuilt/common/fonts/Voltaire.ttf:system/fonts/Voltaire.ttf
